version: 2

sources:
  - name: raw
    database: molten-nirvana-477615-c9
    schema: gz_raw_data
    loader: bigquery
    description: Raw data tables loaded from the gz_raw_data dataset in BigQuery.

    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Raw sales transactions including order amounts and dates.

      - name: product
        identifier: raw_gz_product
        description: Raw product catalog including product attributes.

      - name: ship
        identifier: raw_gz_ship
        description: Raw shipping information for each order.